services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      env_file: .env.production
    depends_on:
      db:
        condition: service_healthy
    restart: always
  
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=npg_RXAz2JslEcZ3
      - POSTGRES_DB=neondb?sslmode=require&channel_binding=require
    volumes:
      - pgdata:/var/lib/postgresql/datadocker compose exec app sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres","wget --quiet --tries=1 --spider http://localhost:3000" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

volumes:
  pgdata: