// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { readFileSync } from "node:fs";
import { defineConfig } from "prisma/config";

function readDatabaseUrl() {
  const directValue = process.env["DATABASE_URL"]?.trim();
  if (directValue) {
    return directValue;
  }

  const filePath = process.env["DATABASE_URL"]?.trim();
  if (!filePath) {
    return undefined;
  }

  try {
    const fileValue = readFileSync(filePath, "utf8").trim();
    return fileValue || undefined;
  } catch {
    return undefined;
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: readDatabaseUrl(),
  },
});
